name: PR Check Workflow
on: pull_request
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: microsoft
          
      - name: Install g++
        run: sudo apt-get install g++
        
      - name: Setup Gradle and Install Roborio Toolchain
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: current
          arguments: installRoboRioToolchain
          
      - name: Get Compile Commands
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: current
          arguments: generateCompileCommands
      
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          database: 'build/compile_commands/linuxathena'
          extra-args: '-stdlib=libstdc++'
          
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
    
  build-executable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: microsoft
    - name: Setup Gradle and Install Roborio Toolchain
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: current
        arguments: installRoboRioToolchain
    - name: Build Roborio Executable
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: current
        arguments: frcUserProgramReleaseExecutable
