name: PR Check Workflow
on: pull_request
jobs:
  build-and-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install build-essential
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: microsoft
          
      - name: Setup Gradle and Install Roborio Toolchain
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: current
          arguments: installRoboRioToolchain
          
      - name: Build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: current
          arguments: frcUserProgramReleaseExecutable
          
      - name: Get Compile Commands
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: current
          arguments: generateCompileCommands
      
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          database: 'build/compile_commands/linuxathena'
          extra-args: '-stdlib=libstdc++ -I/home/runner/.gradle/toolchains/frc/2022/roborio/arm-frc2022-linux-gnueabi/usr/include/c++/7.3.0 -I/home/runner/.gradle/toolchains/frc/2022/roborio/arm-frc2022-linux-gnueabi/usr/include/ -I/home/runner/.gradle/toolchains/frc/2022/roborio/arm-frc2022-linux-gnueabi/usr/include/c++/7.3.0/arm-frc2022-linux-gnueabi'
          
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
