name: Gradle Build on PRs
on: pull_request
jobs:
  gradle:
    runs-on: windows-latest
    steps:
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: current
        arguments: frcUserProgramReleaseExecutable
